import { CountryTimeZone } from "@interfaces/country.interface";

export const COUNTRIES_LIST: CountryTimeZone[] = [
  {
    value: 'world',
    name: 'Resto del Mundo',
    imgFlag: 'assets/images/flags/glo.png',
    id: '',
    code: '',
    languageId: '',
    isoCurrency: '',
    isoCode: '',
  },
  {
    value: 'CR',
    name: 'Costa Rica',
    imgFlag: 'assets/images/flags/crc.png',
    id: '',
    code: '',
    languageId: '',
    isoCurrency: '',
    isoCode: '',
  },
  {
    value: 'AR',
    name: 'Argentina',
    imgFlag: 'assets/images/flags/arg.png',
    id: '',
    code: '',
    languageId: '',
    isoCurrency: '',
    isoCode: '',
  },
  {
    value: 'BO',
    name: 'Bolivia',
    imgFlag: 'assets/images/flags/bol.png',
    id: '',
    code: '',
    languageId: '',
    isoCurrency: '',
    isoCode: '',
  },
  {
    value: 'BR',
    name: 'Brasil',
    imgFlag: 'assets/images/flags/bra.png',
    id: '',
    code: '',
    languageId: '',
    isoCurrency: '',
    isoCode: '',
  },
  {
    value: 'CL',
    name: 'Chile',
    imgFlag: 'assets/images/flags/chi.png',
    id: '',
    code: '',
    languageId: '',
    isoCurrency: '',
    isoCode: '',
  },
  {
    value: 'CO',
    name: 'Colombia',
    imgFlag: 'assets/images/flags/col.png',
    id: '',
    code: '',
    languageId: '',
    isoCurrency: '',
    isoCode: '',
  },
  {
    value: 'CU',
    name: 'Cuba',
    imgFlag: 'assets/images/flags/cub.png',
    id: '',
    code: '',
    languageId: '',
    isoCurrency: '',
    isoCode: '',
  },
  {
    value: 'DO',
    name: 'Rep. Dominicana',
    imgFlag: 'assets/images/flags/rep.png',
    id: '',
    code: '',
    languageId: '',
    isoCurrency: '',
    isoCode: '',
  },
  {
    value: 'EC',
    name: 'Ecuador',
    imgFlag: 'assets/images/flags/ecu.png',
    id: '',
    code: '',
    languageId: '',
    isoCurrency: '',
    isoCode: '',
  },
  {
    value: 'GT',
    name: 'Guatemala',
    imgFlag: 'assets/images/flags/gua.png',
    id: '',
    code: '',
    languageId: '',
    isoCurrency: '',
    isoCode: '',
  },
  {
    value: 'GY',
    name: 'Guyana',
    imgFlag: 'assets/images/flags/gya.png',
    id: '',
    code: '',
    languageId: '',
    isoCurrency: '',
    isoCode: '',
  },
  {
    value: 'HN',
    name: 'Honduras',
    imgFlag: 'assets/images/flags/hon.png',
    id: '',
    code: '',
    languageId: '',
    isoCurrency: '',
    isoCode: '',
  },
  {
    value: 'MX',
    name: 'México',
    imgFlag: 'assets/images/flags/mex.png',
    id: '',
    code: '',
    languageId: '',
    isoCurrency: '',
    isoCode: '',
  },
  {
    value: 'NI',
    name: 'Nicaragua',
    imgFlag: 'assets/images/flags/nic.png',
    id: '',
    code: '',
    languageId: '',
    isoCurrency: '',
    isoCode: '',
  },
  {
    value: 'PA',
    name: 'Panamá',
    imgFlag: 'assets/images/flags/pan.png',
    id: '',
    code: '',
    languageId: '',
    isoCurrency: '',
    isoCode: '',
  },
  {
    value: 'PE',
    name: 'Perú',
    imgFlag: 'assets/images/flags/per.png',
    id: '',
    code: '',
    languageId: '',
    isoCurrency: '',
    isoCode: '',
  },
  {
    value: 'PR',
    name: 'Puerto Rico',
    imgFlag: 'assets/images/flags/pto.png',
    id: '',
    code: '',
    languageId: '',
    isoCurrency: '',
    isoCode: '',
  },
  {
    value: 'SV',
    name: 'El Salvador',
    imgFlag: 'assets/images/flags/els.png',
    id: '',
    code: '',
    languageId: '',
    isoCurrency: '',
    isoCode: '',
  },
  {
    value: 'US',
    name: 'Estados Unidos',
    imgFlag: 'assets/images/flags/usa.png',
    id: '',
    code: '',
    languageId: '',
    isoCurrency: '',
    isoCode: '',
  },
  {
    value: 'UY',
    name: 'Uruguay',
    imgFlag: 'assets/images/flags/uru.png',
    id: '',
    code: '',
    languageId: '',
    isoCurrency: '',
    isoCode: '',
  },
  {
    value: 'VE',
    name: 'Venezuela',
    imgFlag: 'assets/images/flags/ven.png',
    id: '',
    code: '',
    languageId: '',
    isoCurrency: '',
    isoCode: '',
  },
];
